name: Deploy

on:
  push:
    branches:
      - master 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: SSH and deploy
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        echo "$SSH_PRIVATE_KEY" > keyfile
        chmod 600 keyfile
        mkdir -p ~/.ssh
        ssh-keyscan -H ec2-3-110-118-39.ap-south-1.compute.amazonaws.com >> ~/.ssh/known_hosts
        ssh -t -i keyfile -o StrictHostKeyChecking=no ubuntu@ec2-3-110-118-39.ap-south-1.compute.amazonaws.com "sudo bash ~/deploy2.sh" 
